services:
  rabbit_mq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbit_mq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data
    networks:
      - localdev

  producer:
    build: producer
    depends_on:
      - rabbit_mq
      - redis
    volumes:
      - ./producer:/usr/src/app/producer
    networks:
      - localdev

  consumer:
    build: consumer
    depends_on:
        - rabbit_mq
        - redis
    volumes:
      - ./consumer:/usr/src/app/consumer
    networks:
      - localdev

  redis:
    image: redislabs/redistimeseries
    container_name: redis-time-series
    hostname: redislocal
    ports:
      - '6379:6379'
    networks:
      - localdev

  web-server:
    build: web-server
    depends_on:
      - redis
    ports:
      - '8000:8000'
    volumes:
    - type: bind
    # todo: remove
      source: /C/Users/user/PycharmProjects/rabbitmq-docker-master/web-server/app
      target: /code/app
    networks:
      - localdev

volumes:
    rabbit_mqdata:
      driver: local

networks:
  localdev:
    driver: bridge
